<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE context [
        <!ELEMENT context (device | context-attribute)*>
        <!ELEMENT context-attribute EMPTY>
        <!ELEMENT device (channel | attribute | debug-attribute | buffer-attribute)*>
        <!ELEMENT channel (scan-element?, attribute*)>
        <!ELEMENT attribute EMPTY>
        <!ELEMENT scan-element EMPTY>
        <!ELEMENT debug-attribute EMPTY>
        <!ELEMENT buffer-attribute EMPTY>
        <!ATTLIST context name CDATA #REQUIRED description CDATA #IMPLIED>
        <!ATTLIST context-attribute name CDATA #REQUIRED value CDATA #REQUIRED>
        <!ATTLIST device id CDATA #REQUIRED name CDATA #IMPLIED>
        <!ATTLIST channel id CDATA #REQUIRED type (input|output) #REQUIRED name CDATA #IMPLIED>
        <!ATTLIST scan-element index CDATA #REQUIRED format CDATA #REQUIRED scale CDATA #IMPLIED>
        <!ATTLIST attribute name CDATA #REQUIRED filename CDATA #IMPLIED value CDATA #IMPLIED>
        <!ATTLIST debug-attribute name CDATA #REQUIRED value CDATA #IMPLIED>
        <!ATTLIST buffer-attribute name CDATA #REQUIRED value CDATA #IMPLIED>
]>
<context name="xml" description="no-OS analog 1.1.0-g0000000 #1 Tue Nov 26 09:52:32 IST 2019 armv7l">
    <context-attribute name="no-OS" value="1.1.0-g0000000"/>
    <device id="iio:device0" name="ad74413r">
        <channel id="voltage0" type="input">
            <scan-element index="0" format="be:u16/32&gt;&gt;8"/>
            <attribute name="sampling_frequency" filename="sampling_frequency" value="10"/>
            <attribute name="sampling_frequency_available" filename="sampling_frequency_available" value="10 20 1200 4800"/>
            <attribute name="raw" filename="in_voltage0_raw" value="0.1"/>
            <attribute name="scale" filename="in_voltage0_scale" value="0.1"/>
            <attribute name="offset" filename="in_voltage0_offset" value="0"/>
        </channel>
        <channel id="voltage0_diag" name="diag0" type="input">
            <scan-element index="0" format="be:u16/32&gt;&gt;8"/>
            <attribute name="sampling_frequency" filename="sampling_frequency" value="10"/>
            <attribute name="sampling_frequency_available" filename="sampling_frequency_available" value="10 20 1200 4800"/>
            <attribute name="raw" filename="in_voltage0_raw" value="0.2"/>
            <attribute name="scale" filename="in_voltage0_scale" value="0.1"/>
            <attribute name="offset" filename="in_voltage0_offset" value="0"/>
        </channel>
        <channel id="voltage1_diag" name="diag1" type="input">
            <scan-element index="0" format="be:u16/32&gt;&gt;8"/>
            <attribute name="sampling_frequency" filename="sampling_frequency" value="10"/>
            <attribute name="sampling_frequency_available" filename="sampling_frequency_available" value="10 20 1200 4800"/>
            <attribute name="raw" filename="in_voltage1_raw" value="0.2"/>
            <attribute name="scale" filename="in_voltage1_scale" value="0.1"/>
            <attribute name="offset" filename="in_voltage1_offset" value="0"/>
        </channel>
        <channel id="voltage2_diag" name="diag2" type="input">
            <scan-element index="0" format="be:u16/32&gt;&gt;8"/>
            <attribute name="sampling_frequency" filename="sampling_frequency" value="10"/>
            <attribute name="sampling_frequency_available" filename="sampling_frequency_available" value="10 20 1200 4800"/>
            <attribute name="raw" filename="in_voltage2_raw" value="0.2"/>
            <attribute name="scale" filename="in_voltage2_scale" value="0.1"/>
            <attribute name="offset" filename="in_voltage2_offset" value="0"/>
        </channel>
        <channel id="voltage3_diag" name="diag3" type="input">
            <scan-element index="0" format="be:u16/32&gt;&gt;8"/>
            <attribute name="sampling_frequency" filename="sampling_frequency" value="10"/>
            <attribute name="sampling_frequency_available" filename="sampling_frequency_available" value="10 20 1200 4800"/>
            <attribute name="raw" filename="in_voltage3_raw" value="0.2"/>
            <attribute name="scale" filename="in_voltage3_scale" value="0.1"/>
            <attribute name="offset" filename="in_voltage3_offset" value="0"/>
        </channel>
        <channel id="current1" type="input">
            <scan-element index="1" format="be:u16/32&gt;&gt;8"/>
            <attribute name="sampling_frequency" filename="sampling_frequency" value="10"/>
            <attribute name="sampling_frequency_available" filename="sampling_frequency_available" value="10 20 1200 4800"/>
            <attribute name="raw" filename="in_current1_raw" value="0.1"/>
            <attribute name="scale" filename="in_current1_scale" value="0.1"/>
            <attribute name="offset" filename="in_current1_offset" value="0"/>
        </channel>
        <channel id="voltage2" type="input">
            <scan-element index="2" format="be:u16/32&gt;&gt;8"/>
            <attribute name="sampling_frequency" filename="sampling_frequency" value="10"/>
            <attribute name="sampling_frequency_available" filename="sampling_frequency_available" value="10 20 1200 4800"/>
            <attribute name="raw" filename="in_voltage2_raw" value="0.1"/>
            <attribute name="scale" filename="in_voltage2_scale" value="0.1"/>
            <attribute name="offset" filename="in_voltage2_offset" value="0"/>
        </channel>
        <channel id="voltage3" type="input">
            <scan-element index="3" format="be:u16/32&gt;&gt;8"/>
            <attribute name="sampling_frequency" filename="sampling_frequency" value="10"/>
            <attribute name="sampling_frequency_available" filename="sampling_frequency_available" value="10 20 1200 4800"/>
            <attribute name="raw" filename="in_voltage3_raw" value="0.1"/>
            <attribute name="scale" filename="in_voltage3_scale" value="0.1"/>
            <attribute name="offset" filename="in_voltage3_offset" value="0"/>
        </channel>
        <channel id="voltage1" type="output">
            <attribute name="raw" filename="out_voltage1_raw" value="0.1"/>
            <attribute name="scale" filename="out_voltage1_scale" value="0.1"/>
            <attribute name="offset" filename="out_voltage1_offset" value="0"/>
            <attribute name="slew_en" filename="out_voltage1_slew_en" value="0.1"/>
            <attribute name="slew_rate" filename="out_voltage1_slew_rate" value="0.1"/>
            <attribute name="slew_rate_available" filename="out_slew_rate_available" value="0.1"/>
            <attribute name="slew_step" filename="out_voltage1_slew_step" value="0.1"/>
            <attribute name="slew_step_available" filename="out_slew_step_available" value="0.1"/>
        </channel>
        <channel id="current2" type="output">
            <attribute name="raw" filename="out_current2_raw" value="0.1"/>
            <attribute name="scale" filename="out_current2_scale" value="0.1"/>
            <attribute name="offset" filename="out_current2_offset" value="0"/>
            <attribute name="slew_en" filename="out_current2_slew_en" value="0.1"/>
            <attribute name="slew_rate" filename="out_current2_slew_rate" value="0.1"/>
            <attribute name="slew_rate_available" filename="out_slew_rate_available" value="0.1"/>
            <attribute name="slew_step" filename="out_current2_slew_step" value="0.1"/>
            <attribute name="slew_step_available" filename="out_slew_step_available" value="0.1"/>
        </channel>
        <channel id="voltage" name="fault" type="input">
            <attribute name="raw" filename="in_voltage_raw" value="0.1"/>
        </channel>
        <debug-attribute name="direct_reg_access" value="0.1"/>
    </device>
    <device id="iio:device1" name="max14906">
        <channel id="voltage0" type="input">
            <attribute name="raw" filename="in_voltage0_raw" value="0.1"/>
            <attribute name="offset" filename="in_voltage0_offset" value="0"/>
            <attribute name="scale" filename="in_voltage0_scale" value="0.1"/>
        </channel>
        <channel id="voltage1" type="input">
            <attribute name="raw" filename="in_voltage1_raw" value="0.1"/>
            <attribute name="offset" filename="in_voltage1_offset" value="0"/>
            <attribute name="scale" filename="in_voltage1_scale" value="0.1"/>
        </channel>
        <channel id="voltage2" type="input">
            <attribute name="raw" filename="in_voltage2_raw" value="0.1"/>
            <attribute name="offset" filename="in_voltage2_offset" value="0"/>
            <attribute name="scale" filename="in_voltage2_scale" value="0.1"/>
        </channel>
        <channel id="voltage3" type="input">
            <attribute name="raw" filename="in_voltage3_raw" value="0.1"/>
            <attribute name="offset" filename="in_voltage3_offset" value="0"/>
            <attribute name="scale" filename="in_voltage3_scale" value="0.1"/>
        </channel>
        <channel id="voltage" name="fault" type="input">
            <attribute name="raw" filename="in_voltage_raw" value="0.1"/>
        </channel>
        <debug-attribute name="direct_reg_access" value="0.1"/>
    </device>
</context>